name: Stage PR workflow

on:
  pull_request:
    branches:
      - main

env:
  DAY_OF_WEEK: |
    - value: {}

jobs:
  list-products:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls products/*.json | jq -R -s -c 'split("\n")[:-1]')"


  read-file:
    needs: list-products
    runs-on: ubuntu-latest
    strategy:
        matrix:
            manifest: ${{ fromJson(needs.list-products.outputs.matrix) }}
    outputs:
      matrix-json: ${{ steps.read_file.outputs.contents }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: ${{ matrix.manifest }}
      
      - name: Save file contents
        run: |
          IFS="," read -a myarray <<< ${{ fromJson(steps.read_file.outputs.contents) }}
          for i in "${myarray[@]}"; do
            echo "${{fromJson(steps.read_file.outputs.contents)}}"
          done
        # echo ::set-output name=arr::${arr[@]}
        # run: echo "::set-output name=matrix-json::${{concat(somevar, 1)}}"
        #runs-on: ${{ concat(somevar, steps.read_file.outputs.contents) }}
        # run: |
        #   script: |
        #     somevar=[...somevar, ...steps.read_file.outputs.contents]
        #     echo "::set-output name=matrix-json::$somevar"
        # run: |
        #   export appjson='["${{steps.read_file.outputs.contents}}"]'
        #   echo "::set-output name=matrix-json::$appjson"
        # run: echo "::set-output name=matrix-json::${{steps.read_file.outputs.contents}}"

      - name: File contents
        run: echo "${{ steps.read_file.outputs.contents }}"

  check:
    needs: read-file
    runs-on: ubuntu-latest
    strategy:
        matrix:
            manifest: ${{ fromJson(needs.read-file.outputs.matrix-json) }}
    steps:
      - uses: actions/checkout@v2   
      - run: |
          echo "${{ matrix.manifest }}"
          
        # TODO: Trigger the workflow based on the variable repo